name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *" # 每 12 小時執行一次 (UTC 00:00, 12:00)
  workflow_dispatch:      # 保留手動觸發功能

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: a2oon/actions-sync-fork@v1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: HegeKen/HyperData # 記得替換成原作者/專案名
          target_branch: tw_version           # 你的分支
          upstream_branch: main         # 原專案分支
