name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *" # 每 12 小時執行一次 (UTC 00:00, 12:00)
  workflow_dispatch:      # 保留手動觸發功能

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: tw_version # 確保切換到正確的分支

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: HegeKen/HyperData
          upstream_sync_branch: main
          target_sync_branch: tw_version
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."
